
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoJJjN4Lg7qcFT7Az3ySeul6uQOBMG4Hc',
    authDomain: 'unisafe-4ad0a.firebaseapp.com',
    projectId: 'unisafe-4ad0a',
    storageBucket: 'unisafe-4ad0a.appspot.com',
    messagingSenderId: '303215283767',
    appId: '1:303215283767:web:f7ee5e5f991af278bcb9b2'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD49Qvz1i5T6qPYmF7s9eK9kYooYh6hkSg',
    appId: '1:303215283767:android:908428fa76699d07bcb9b2',
    messagingSenderId: '303215283767',
    projectId: 'unisafe-4ad0a',
    storageBucket: 'unisafe-4ad0a.appspot.com'
  );
}
